src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductsRepository::class)
 */
class Products
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ProdName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $addAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="integer")
     */
    private $priceArtist;

    /**
     * @ORM\Column(type="integer")
     */
    private $priceSite;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $views;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $likes;

    /**
     * @ORM\Column(type="integer")
     */
    private $categoryId;

    /**
     * @ORM\Column(type="integer")
     */
    private $artistId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProdName(): ?string
    {
        return $this->ProdName;
    }

    public function setProdName(string $ProdName): self
    {
        $this->ProdName = $ProdName;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAddAt(): ?\DateTimeInterface
    {
        return $this->addAt;
    }

    public function setAddAt(\DateTimeInterface $addAt): self
    {
        $this->addAt = $addAt;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(?string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->quantity;
    }

    public function setQuantity(string $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPriceArtist(): ?int
    {
        return $this->priceArtist;
    }

    public function setPriceArtist(int $priceArtist): self
    {
        $this->priceArtist = $priceArtist;

        return $this;
    }

    public function getPriceSite(): ?int
    {
        return $this->priceSite;
    }

    public function setPriceSite(int $priceSite): self
    {
        $this->priceSite = $priceSite;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(?int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->likes;
    }

    public function setLikes(?int $likes): self
    {
        $this->likes = $likes;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->categoryId;
    }

    public function setCategoryId(?int $categoryId): self
    {
        $this->categoryId = $categoryId;

        return $this;
    }

    public function getArtistId(): ?int
    {
        return $this->artistId;
    }

    public function setArtistId(int $artistId): self
    {
        $this->artistId = $artistId;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Products;
use App\Repository\ProductsRepository;
use phpDocumentor\Reflection\DocBlock\Tags\Var_;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="index")
     */
    public function index(ProductsRepository $repo)
    {
        
        $products = $repo->findAll();
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'products' => $products   
        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function home()
    {
        return $this->render('home/home.html.twig', [
            'title' => "Bienvenue sur la page d'acceil!",

        ]);

    }
    
    /**
     * @Route("/home/new", name="home_create")
     */

    public function create(){
        return $this->render('home/create.html.twig');
    }


    /**
     * @Route("/home/{id}", name="home_show")
     */

    public function show(Products $products){

        return $this->render('home/show.html.twig', [
            'products' => $products
            ]);
    }



}

templates/home/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<section class="fullscreen fullscreen_form">
 <div class="example-wrapper">
  <h1>Creation d'un...
  </h1>
  <div class="fullscreen__img">
  <img src="{{ baseUri }}/assets/img/BigLogo.png" alt="logo" />
  </div>
 </div>
</section>

{% endblock %}

templates/home/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!--
<h1>{{ title }}</h1> -->
        <section class="fullscreen">
            <div class="fullscreen__body">
                 <!--<h1 class="fullscreen__title">HELLo!</h1>
                <div class="fullscreen__text">
                     Wellcome to our site!</div>-->
 <div id="img_art"><img src="{{ baseUri }}/assets/img/Artshop.png" alt="Artshop" /></div>
            </div>
           
            
        </section>
        <section class="fullscreen fullscreen_two" id="about">
        
    <div class="fullscreen__body_two">
      <div class="fullscreen__body_two">
                <h1 class="fullscreen__title">Hello!</h1>
                <div class="fullscreen__text_about">
                      Are you looking for a beautiful, suitable picture for your apartment or office? Our small group of creative artists will help you with this. A wide selection and good quality of the paintings presented on our website (whether classic, romantic or modern) will satisfy any taste. We are glad to see you! Enjoy your shopping!</div>

            </div>


    
    </div>
        </section>
        <section class="fullscreen fullscreen_three">
            <div class="fullscreen__body">
                <h1 class="fullscreen__title">BUY BUY!</h1>
                <div class="fullscreen__text">
                    See you soon!
                    
                </div>
                <a href="" class="fullscreen__link">BACK</a>
            </div>
        </section>

{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    
<section class="fullscreen fullscreen_index">

<div class="example-wrapper">

    <h1>Hello Salut {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/Artshop/src/Controller/HomeController.php'|file_link(0) }}">src/Controller/HomeController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/Artshop/templates/home/index.html.twig'|file_link(0) }}">templates/home/index.html.twig</a></code></li>
        <li>

        {% for products in products %}

            <h2>{{ products.prodName }}</h2>
           
            <p>
                {{ products.description | raw }}
                Added at {{ products.addAt | date('m/d/Y') }} at {{ products.addAt | date('H:i') }}
                <img src = "{{ products.image }}" alt="">
            <a href="{{ path('home_show', { 'id': products.id }) }}" class="btn btn-primary">Lire la suite</a>
            </p>

        
        {% endfor %}

</li>
    </ul>
    
</div>
</section>

{% endblock %}

templates/home/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<section class="fullscreen">
<div class="show">
   <p>Bonjour</p> 
  
   <h2>{{ products.prodName }}</h2>
   <div class="fullscreen__img">
   <img src="{{ baseUri }}/assets/img/BigLogo.png" alt="logo" />
   </div>
</div>
</section>
{% endblock %}